name: PR Checks

on:
  pull_request:
    branches: [ main ]

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run verifications
        run: ./gradlew check --scan

      - name: Run validate on ui
        run: ./gradlew :ui:check --scan

      - name: Run validate on core
        run: ./gradlew :core:check --scan

      - name: Run validate on plugin
        run: ./gradlew :gross-plugin:check :gross-plugin:validatePlugins --scan

      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'