name: PR Checks

on:
  pull_request:
    branches: [ main ]

# Ensures that only one deploy task per branch/environment will run at a time.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: "Find version"
        id: find_version
        run: ./scripts/generate_versions.sh

      - name: Run verifications
        run: ./gradlew check --scan

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'

  ui-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: "Find version"
        id: find_version
        run: ./scripts/generate_versions.sh

      - name: Run validate on ui
        run: ./gradlew :ui:check --scan

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'

  core-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: "Find version"
        id: find_version
        run: ./scripts/generate_versions.sh

      - name: Run validate on core
        run: ./gradlew :core:check --scan

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'

  plugin-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: "Find version"
        id: find_version
        run: ./scripts/generate_versions.sh

      - name: Run validate on plugin
        working-directory: gross-plugin
        run: ./gradlew check validatePlugins --scan

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'
